apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: banti47/todo-app-week-39:76d02a5d4aac69e6815e5c1066f02afc5104e777
      ports:
        - containerPort: 80
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: httpd
#   labels:
#     app: nginx
# spec:
#   containers:
#     - name: httpd
#       image: httpd
#       ports:
#         - containerPort: 80
